services:
  cluster-state:
    image: kubegraph-cluster-state:latest
    container_name: cluster-state
    volumes:
      - /kubeconf:/kubeconf
    restart: unless-stopped
    networks:
      - cluster-state

networks:
  cluster-state:

volumes:
  kubeconfig:
    driver: local
